[project]
name = "ilab-gipfeli"
version = "0.1.0"
description = "A project by iLab Kanti Glarus."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-telegram-bot>=22.5",
    "bosdyn-client>=4.0.0",
    "bosdyn-mission>=4.0.0",
    "python-dotenv>=1.0.0",
]
